server:
  port: 9001

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Leo-ry/spring-config-server
          default-label: master
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5682
    username: leona
    password: leona
    